kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-react-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deploy-react-kubernetes
  template:
    metadata:
      labels:
        app: deploy-react-kubernetes
    spec:
      containers:
        - name: deploy-react-kubernetes
          image: eljilisa/deploy-react-kubernetes
          ports:
            - containerPort: 80
